name: Deploy VuePress

on:
  push:
    branches:
      - main # 当 main 分支有更新时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

#      - name: Setup Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: 22

      # 安装 pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
        version: 9


      - name: Install dependencies
        run: pnpm install

      - name: Build VuePress
        run: pnpm docs:build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
          with:
            # 部署到 gh-pages 分支
            target_branch: gh-pages
            # 部署目录为 VuePress 的默认输出目录
            build_dir: docs/.vuepress/dist
          env:
            # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
